configuration: Release

image:
  - Visual Studio 2017
  
cache:
  - packages -> **\packages.config

before_build:
  - git submodule update --init
  - nuget restore
  
build:
  project: FFXIVTool.sln
    
after_build:
  7z a FFXIVTool.zip %APPVEYOR_BUILD_FOLDER%\FFXIVTool\bin\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\FFXIVTool\bin\%CONFIGURATION%\*.txt %APPVEYOR_BUILD_FOLDER%\FFXIVTool\bin\%CONFIGURATION%\OffsetSettings.xml %APPVEYOR_BUILD_FOLDER%\FFXIVTool\bin\%CONFIGURATION%\ex.json %APPVEYOR_BUILD_FOLDER%\FFXIVTool\bin\%CONFIGURATION%\exview.json
    
artifacts:
  - path: FFXIVTool.zip
    name: FFXIVTool

deploy:
  tag: $(appveyor_repo_tag_name)
  release: Screenshot Helper $(appveyor_repo_tag_name)
  provider: GitHub
  draft: true
  auth_token:
    secure: O6Rsj+hoS5X7Q1u7TjtFwjRN53ohwjF8Mik/BpVidoefAag5FfpxoWqS5GTdJECG
  artifact: FFXIVTool.zip
  on:
    branch: master
    appveyor_repo_tag: true
